### PR TITLE
Fix self-reference for recursive app navigation entries

### PR DESCRIPTION
**Pull request by ChristophWurst**

### CODE REVIEW

**Comment by ChristophWurst** [comment]
Tests are for the weak

**Comment by skjnldsv** [comment]
@skjnldsv merge

**Comment by ChristophWurst** [comment]
is that a bad imitation of @dependabot?

bildschirmfoto von 2018-11-12 15-02-05

**Comment by skjnldsv** [comment]
Shhhhh

**Comment by ChristophWurst** [comment]
It's [carnival](https://en.wikipedia.org/wiki/Carnival_in_Germany,_Switzerland_and_Austria9) after all :robot:

**Pull request merged**
