### PR TITLE
Wrap Multiselect

### LINKED ISSUE #91: Remove height attribute for .multiselect[...] .multiselect__content-wrapper li > span
The height of the options in the dropdown is fixed to 20px and cuts out the template for the 'option' slot. Changing height to min-height?

https://github.com/nextcloud/vue-components/blob/6035e15ca2d87e74b3402cf4976ed650b5fa8eff/src/components/Multiselect/index.scss#L147

grafik

### PR DESCRIPTION
**Pull request by skjnldsv**
After #70 
Fix #91
- [x] Create options standards for Multiselect
- [x] Slots
- [x] Style fixes

### Examples
Default style
``` html
<Multiselect :options="options" v-model="select" />
```
Default style multiple with auto width calculation (default option width is 150px)
You can set the min with `:tag-width="80"`
``` html
<Multiselect :options="options" v-model="select" :multiple="true" />`
```
Disable auto width calculation (always show max XXX entries)
``` html
<Multiselect :options="options" v-model="select" :multiple="true" :auto-limit="false" :limit="XXX" />`
```
Avatar select option
``` html
<Multiselect :options="options" v-model="select" label="displayName" track-by="user" :multiple="true" :user-select="true" />`
```

capture d ecran_2018-11-08_16-36-37

### CODE REVIEW

**Comment by ChristophWurst** [comment]
> Default style multiple with auto width calculation (default option width is 150px)
> You can set the min with `:tag-width="80"`

What does that mean? Where do I need that?

> label="displayName" track-by="user"

Are these props on the data?

**Comment by skjnldsv** [comment]
> What does that mean? Where do I need that?

It is the minimum width for the selected options. It will be calculated to create the limit popup.
If you set it to 80px, the min-width of the options will be to 80px. Since we use flex-shrink. Any more items that don't fit will be put in the `+xxx` popup :)
peek 09-11-2018 11-03

> Are these props on the data?

This is the normal props you can use on the multiselect lib to define which keys to use on the object options.
You will need options formatted like that:
```
{
	desc: 'This is the admin',
	displayName: 'Admin',
	icon: 'icon-user',
	user: 'admin'
}
```

**Comment by ChristophWurst** [comment]
Idea for a future enhancement: a standard for the loading state (loading more data dynamically, https://github.com/shentao/vue-multiselect#asynchronous-dropdown)

**Comment by skjnldsv** [comment]
> Idea for a future enhancement: a standard for the loading state (loading more data dynamically, https://github.com/shentao/vue-multiselect#asynchronous-dropdown)

Yes, That's what I was talking in your issue #81

**Pull request merged**
